import { Announcement, RequestObject, RecordObject, Patient } from '@/app/demo/demo-types';

// Dummy array of Patients
export const patients: Patient[] = [
  {
    pid: 'pid1',
    name: 'Tom Reece',
    email: 'tom.reece@example.com',
    phoneNumber: '858-555-1234',
    DOB: '1980-05-15',
    gender: 'male',
    password: 'hashed_password1',
    insurance: 'HealthFirst',
    primaryCareProvider: 'Dr. John Doe',
    lastSeen: 'Street Corner Care',
    profilePicture: 'profile_tom.jpg',
    records: ['randomId1'],
    emailVerify: true,
    phoneVerify: true,
  },
  {
    pid: 'pid2',
    name: 'Jane Doe',
    email: 'jane.doe@example.com',
    phoneNumber: '858-555-5678',
    DOB: '1975-09-20',
    gender: 'female',
    password: 'hashed_password2',
    insurance: 'Medicare',
    primaryCareProvider: 'Dr. Emily Clark',
    lastSeen: 'Street Corner Care',
    profilePicture: 'profile_jane.jpg',
    records: ['randomId2', 'randomId3'],
    emailVerify: true,
    phoneVerify: true,
  },
  {
    pid: 'pid3',
    name: 'Jane Doe',
    email: 'jane.doe2@example.com',
    phoneNumber: '858-555-8765',
    DOB: '1975-09-20',
    gender: 'female',
    password: 'hashed_password3',
    insurance: 'Medicare',
    primaryCareProvider: 'Dr. John Doe',
    lastSeen: 'Street Corner Care',
    profilePicture: 'profile_jane_doe.jpg',
    records: ['randomId3'],
    emailVerify: true,
    phoneVerify: true,
  },
  {
    pid: 'pid4',
    name: 'Alice Johnson',
    email: 'alice.johnson@example.com',
    phoneNumber: '858-555-2345',
    DOB: '1990-02-12',
    gender: 'female',
    password: 'hashed_password4',
    insurance: 'BlueCross',
    primaryCareProvider: 'Dr. Lisa Kim',
    lastSeen: 'Street Corner Care',
    profilePicture: 'profile_alice.jpg',
    records: ['randomId4'],
    emailVerify: true,
    phoneVerify: true,
  },
  {
    pid: 'pid5',
    name: 'Robert Brown',
    email: 'robert.brown@example.com',
    phoneNumber: '858-555-3456',
    DOB: '1985-07-18',
    gender: 'male',
    password: 'hashed_password5',
    insurance: 'Aetna',
    primaryCareProvider: 'Dr. Mark Brown',
    lastSeen: 'Street Corner Care',
    profilePicture: 'profile_robert.jpg',
    records: ['randomId5'],
    emailVerify: true,
    phoneVerify: true,
  },
  {
    pid: 'pid6',
    name: 'Emily Davis',
    email: 'emily.davis@example.com',
    phoneNumber: '858-555-4567',
    DOB: '1978-11-25',
    gender: 'female',
    password: 'hashed_password6',
    insurance: 'Cigna',
    primaryCareProvider: 'Dr. Susan Miller',
    lastSeen: 'Street Corner Care',
    profilePicture: 'profile_emily.jpg',
    records: ['randomId6'],
    emailVerify: true,
    phoneVerify: true,
  },
  {
    pid: 'pid7',
    name: 'Michael Wilson',
    email: 'michael.wilson@example.com',
    phoneNumber: '858-555-5678',
    DOB: '1992-03-10',
    gender: 'male',
    password: 'hashed_password7',
    insurance: 'UnitedHealthCare',
    primaryCareProvider: 'Dr. Andrew Wilson',
    lastSeen: 'Street Corner Care',
    profilePicture: 'profile_michael.jpg',
    records: ['randomId7'],
    emailVerify: true,
    phoneVerify: true,
  },
  {
    pid: 'pid8',
    name: 'Sarah Lee',
    email: 'sarah.lee@example.com',
    phoneNumber: '858-555-6789',
    DOB: '1983-04-17',
    gender: 'female',
    password: 'hashed_password8',
    insurance: 'HealthFirst',
    primaryCareProvider: 'Dr. Emily Wright',
    lastSeen: 'Street Corner Care',
    profilePicture: 'profile_sarah.jpg',
    records: ['randomId8'],
    emailVerify: true,
    phoneVerify: true,
  },
  {
    pid: 'pid9',
    name: 'David Harris',
    email: 'david.harris@example.com',
    phoneNumber: '858-555-7890',
    DOB: '1972-08-06',
    gender: 'male',
    password: 'hashed_password9',
    insurance: 'Kaiser Permanente',
    primaryCareProvider: 'Dr. George Thompson',
    lastSeen: 'Street Corner Care',
    profilePicture: 'profile_david.jpg',
    records: ['randomId9'],
    emailVerify: true,
    phoneVerify: true,
  },
  {
    pid: 'pid10',
    name: 'Olivia Martinez',
    email: 'olivia.martinez@example.com',
    phoneNumber: '858-555-8901',
    DOB: '1990-12-02',
    gender: 'female',
    password: 'hashed_password10',
    insurance: 'Anthem',
    primaryCareProvider: 'Dr. Victoria Martinez',
    lastSeen: 'Street Corner Care',
    profilePicture: 'profile_olivia.jpg',
    records: ['randomId10'],
    emailVerify: true,
    phoneVerify: true,
  },
  {
    pid: 'pid11',
    name: 'James Clark',
    email: 'james.clark@example.com',
    phoneNumber: '858-555-9012',
    DOB: '1988-09-08',
    gender: 'male',
    password: 'hashed_password11',
    insurance: 'Humana',
    primaryCareProvider: 'Dr. Olivia Clark',
    lastSeen: 'Street Corner Care',
    profilePicture: 'profile_james.jpg',
    records: ['randomId11'],
    emailVerify: true,
    phoneVerify: true,
  },
  {
    pid: 'pid12',
    name: 'Sophia Rodriguez',
    email: 'sophia.rodriguez@example.com',
    phoneNumber: '858-555-0123',
    DOB: '1995-01-22',
    gender: 'female',
    password: 'hashed_password12',
    insurance: 'BlueCross',
    primaryCareProvider: 'Dr. Michael Davis',
    lastSeen: 'Street Corner Care',
    profilePicture: 'profile_sophia.jpg',
    records: ['randomId12'],
    emailVerify: true,
    phoneVerify: true,
  },
];

// Dummy array of announcements
export const announcements: Announcement[] = [
  {
    header: 'Extended Clinic Hours for Winter',
    date: '11/15/2024',
    content:
      'As the colder months approach, we are extending our clinic hours to ensure that everyone has access to the care they need. Starting from December 1st, our clinic will be open from 8:00 AM to 8:00 PM on weekdays and from 9:00 AM to 5:00 PM on weekends. We encourage all volunteers to sign up for additional shifts if they are available.',
    author: 'Volunteer Coordination Team',
  },
  {
    header: 'Free Winter Clothing Distribution',
    date: '11/20/2024',
    content:
      'We are pleased to announce a special event for the distribution of winter clothing for our homeless community members. On December 5th, from 10:00 AM to 4:00 PM, we will be handing out coats, gloves, hats, and blankets at our outreach center. Volunteers are needed to assist with the distribution and to help organize the donations.',
    author: 'Community Outreach Team',
  },
  {
    header:
      'Important Notice: Major Updates to Our EHR System Including Enhanced Security Protocols, New User Interface Features, Extended Data Integration Capabilities, and Improved Performance Metrics to Better Serve Our Medical Outreach Initiatives',
    date: '11/22/2024',
    content:
      'We are excited to announce a significant update to our Electronic Health Record (EHR) system, which will include several new features and enhancements. These updates are designed to improve the security, usability, and performance of our system, ensuring that our medical outreach teams can operate more efficiently and effectively. Key updates include enhanced security protocols, a redesigned user interface, extended data integration capabilities, and improved performance metrics. We encourage all users to familiarize themselves with the new features and provide feedback to help us continue improving the system.',
    author: 'Technical Development Team',
  },
  {
    header: 'Free Meals During the Holidays',
    date: '12/01/2024',
    content:
      'We know the holidays can be a difficult time for many, so we are organizing free meals throughout December. Our outreach center will serve hot meals every day from December 15th to December 25th, from 12:00 PM to 2:00 PM. We are also collecting donations of non-perishable food items, which can be dropped off at the center anytime during business hours.',
    author: 'Meal Program Coordinator',
  },
  {
    header: 'Temporary Shelter and Warm Spaces Available',
    date: '12/05/2024',
    content:
      'We are opening temporary shelters and warm spaces for those in need during the coldest nights of the winter. Starting from December 10th, these shelters will be open from 6:00 PM to 8:00 AM daily. We are seeking volunteers to help manage the spaces, provide warm beverages, and offer companionship during the night. Please consider signing up for a shift to support this crucial initiative.',
    author: 'Shelter Operations Team',
  },
];

// Dummy array of requests
export const requests: RequestObject[] = [
  {
    patientName: 'Tom Reece',
    correspondingRecord: 'randomId1',
    newPatient: true,
    chiefComplaint: 'headache and wound infection',
    createdAt: '04:25pm',
  },
  {
    patientName: 'Jane Doe',
    correspondingRecord: 'randomId2',
    newPatient: false,
    chiefComplaint: 'chronic back pain',
    createdAt: '05:10pm',
  },
  {
    patientName: 'Jane Doe',
    correspondingRecord: 'randomId3',
    newPatient: false,
    chiefComplaint:
      'Patient is experiencing persistent, sharp chest pain that radiates to the left arm and neck, accompanied by shortness of breath, dizziness, and episodes of profuse sweating. The patient reports that the pain intensifies with physical activity and subsides slightly with rest. Additionally, there has been a noticeable increase in heart palpitations and fatigue over the past week. The patient is also experiencing occasional episodes of nausea and a general feeling of unease, raising concerns about potential cardiac issues.',
    createdAt: '08:30am',
  },
  {
    patientName: 'Alice Johnson',
    correspondingRecord: 'randomId4',
    newPatient: false,
    chiefComplaint: 'skin rash',
    createdAt: '07:45pm',
  },
  {
    patientName: 'Robert Brown',
    correspondingRecord: 'randomId5',
    newPatient: true,
    chiefComplaint: 'shortness of breath',
    createdAt: '08:30pm',
  },
  {
    patientName: 'Emily Davis',
    correspondingRecord: 'randomId6',
    newPatient: false,
    chiefComplaint: 'joint pain',
    createdAt: '09:15pm',
  },
  {
    patientName: 'Michael Wilson',
    correspondingRecord: 'randomId7',
    newPatient: true,
    chiefComplaint: 'abdominal pain',
    createdAt: '10:05pm',
  },
  {
    patientName: 'Sarah Lee',
    correspondingRecord: 'randomId8',
    newPatient: false,
    chiefComplaint: 'migraines',
    createdAt: '10:45pm',
  },
  {
    patientName: 'David Harris',
    correspondingRecord: 'randomId9',
    newPatient: true,
    chiefComplaint: 'chest pain',
    createdAt: '11:30pm',
  },
  {
    patientName: 'Olivia Martinez',
    correspondingRecord: 'randomId10',
    newPatient: false,
    chiefComplaint: 'dizziness',
    createdAt: '12:15am',
  },
  {
    patientName: 'James Clark',
    correspondingRecord: 'randomId11',
    newPatient: true,
    chiefComplaint: 'fatigue and weakness',
    createdAt: '01:00am',
  },
  {
    patientName: 'Sophia Rodriguez',
    correspondingRecord: 'randomId12',
    newPatient: false,
    chiefComplaint: 'allergic reaction',
    createdAt: '01:45am',
  },
];

// Dummy array of records
export const records: RecordObject[] = [
  {
    recordId: 'randomId1',
    recordType: 'standard',
    smokingStatus: 'non-smoker',
    pregnancyStatus: 'not pregnant',
    chronicCondition: 'hypertension',
    currentMedications: 'Lisinopril',
    allergies: 'None',
    chiefComplaint: 'headache and wound infection',

    vitals: {
      temperature: 98.6,
      systolicBloodPressure: 130,
      diastolicBloodPressure: 85,
      pulse: 75,
      oxygen: 98,
      glucose: 90,
    },

    soap: {
      subjective: 'Patient reports mild headache and occasional dizziness.',
      objective: 'Vital signs are within normal limits, no acute distress.',
      assessment: 'Hypertension, managed with current medication.',
    },

    providerName: 'Dr. John Doe',
    scribeName: 'Jane Smith',
    owner: 'pid1',

    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    recordId: 'randomId2',
    recordType: 'standard',
    smokingStatus: 'former smoker',
    pregnancyStatus: 'not pregnant',
    chronicCondition: 'chronic back pain',
    currentMedications: 'Ibuprofen, Muscle relaxants',
    allergies: 'Penicillin',
    chiefComplaint: 'chronic back pain',

    vitals: {
      temperature: 98.1,
      systolicBloodPressure: 120,
      diastolicBloodPressure: 80,
      pulse: 72,
      oxygen: 97,
      glucose: 92,
    },

    soap: {
      subjective: 'Patient reports persistent lower back pain, worse in the morning.',
      objective: 'Tenderness in lumbar region, reduced range of motion.',
      assessment: 'Chronic back pain, likely due to degenerative disc disease.',
    },

    providerName: 'Dr. Emily Clark',
    scribeName: 'Mike Johnson',
    owner: 'pid2',

    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    recordId: 'randomId3',
    recordType: 'urgent',
    smokingStatus: 'non-smoker',
    pregnancyStatus: 'not pregnant',
    chronicCondition: 'hypertension',
    currentMedications: 'Atenolol',
    allergies: 'None',
    chiefComplaint:
      'Patient is experiencing persistent, sharp chest pain that radiates to the left arm and neck, accompanied by shortness of breath, dizziness, and episodes of profuse sweating. The patient reports that the pain intensifies with physical activity and subsides slightly with rest. Additionally, there has been a noticeable increase in heart palpitations and fatigue over the past week. The patient is also experiencing occasional episodes of nausea and a general feeling of unease, raising concerns about potential cardiac issues.',

    vitals: {
      temperature: 98.3,
      systolicBloodPressure: 145,
      diastolicBloodPressure: 90,
      pulse: 85,
      oxygen: 96,
      glucose: 100,
    },

    soap: {
      subjective: 'Patient describes chest pain as sharp and radiating, worsened by exertion.',
      objective: 'Vital signs indicate elevated blood pressure and pulse rate.',
      assessment: 'Possible angina, further cardiac evaluation needed.',
    },

    providerName: 'Dr. John Doe',
    scribeName: 'Anna Williams',
    owner: 'pid3',

    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    recordId: 'randomId4',
    recordType: 'standard',
    smokingStatus: 'non-smoker',
    pregnancyStatus: 'not pregnant',
    chronicCondition: 'none',
    currentMedications: 'None',
    allergies: 'None',
    chiefComplaint: 'skin rash',

    vitals: {
      temperature: 98.7,
      systolicBloodPressure: 118,
      diastolicBloodPressure: 76,
      pulse: 72,
      oxygen: 98,
      glucose: 85,
    },

    soap: {
      subjective: 'Patient reports itchy rash on arms and torso, lasting for 3 days.',
      objective: 'Erythematous rash with small vesicles, no signs of infection.',
      assessment: 'Likely contact dermatitis, recommend topical corticosteroid.',
    },

    providerName: 'Dr. Lisa Kim',
    scribeName: 'John Lee',
    owner: 'pid4',

    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    recordId: 'randomId5',
    recordType: 'urgent',
    smokingStatus: 'non-smoker',
    pregnancyStatus: 'not pregnant',
    chronicCondition: 'asthma',
    currentMedications: 'Albuterol',
    allergies: 'None',
    chiefComplaint: 'shortness of breath',

    vitals: {
      temperature: 98.9,
      systolicBloodPressure: 125,
      diastolicBloodPressure: 82,
      pulse: 88,
      oxygen: 92,
      glucose: 94,
    },

    soap: {
      subjective: 'Patient reports sudden onset of shortness of breath, worse at night.',
      objective: 'Wheezing heard on auscultation, oxygen saturation slightly decreased.',
      assessment: 'Asthma exacerbation, administer bronchodilator.',
    },

    providerName: 'Dr. Mark Brown',
    scribeName: 'Nancy Green',
    owner: 'pid5',

    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    recordId: 'randomId6',
    recordType: 'standard',
    smokingStatus: 'non-smoker',
    pregnancyStatus: 'not pregnant',
    chronicCondition: 'osteoarthritis',
    currentMedications: 'Acetaminophen, Glucosamine',
    allergies: 'None',
    chiefComplaint: 'joint pain',

    vitals: {
      temperature: 98.4,
      systolicBloodPressure: 122,
      diastolicBloodPressure: 78,
      pulse: 70,
      oxygen: 98,
      glucose: 89,
    },

    soap: {
      subjective: 'Patient reports pain in knees and hands, worse with movement.',
      objective: 'Swelling in joints, reduced range of motion.',
      assessment: 'Osteoarthritis, recommend physical therapy and pain management.',
    },

    providerName: 'Dr. Susan Miller',
    scribeName: 'Kevin Parker',
    owner: 'pid6',

    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    recordId: 'randomId7',
    recordType: 'urgent',
    smokingStatus: 'non-smoker',
    pregnancyStatus: 'not pregnant',
    chronicCondition: 'none',
    currentMedications: 'None',
    allergies: 'None',
    chiefComplaint: 'abdominal pain',

    vitals: {
      temperature: 99.1,
      systolicBloodPressure: 124,
      diastolicBloodPressure: 80,
      pulse: 78,
      oxygen: 97,
      glucose: 95,
    },

    soap: {
      subjective: 'Patient reports severe abdominal pain, nausea, and vomiting.',
      objective: 'Abdomen tender on palpation, no rebound tenderness.',
      assessment: 'Possible gastroenteritis or appendicitis, recommend further imaging.',
    },

    providerName: 'Dr. Andrew Wilson',
    scribeName: 'Laura Davis',
    owner: 'pid7',

    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    recordId: 'randomId8',
    recordType: 'standard',
    smokingStatus: 'non-smoker',
    pregnancyStatus: 'not pregnant',
    chronicCondition: 'migraine',
    currentMedications: 'Sumatriptan',
    allergies: 'None',
    chiefComplaint: 'migraines',

    vitals: {
      temperature: 98.2,
      systolicBloodPressure: 120,
      diastolicBloodPressure: 75,
      pulse: 68,
      oxygen: 98,
      glucose: 88,
    },

    soap: {
      subjective: 'Patient reports recurrent migraines, with photophobia and nausea.',
      objective: 'No focal neurological deficits observed.',
      assessment: 'Migraine, continue current medication, consider preventative therapy.',
    },

    providerName: 'Dr. Emily Wright',
    scribeName: 'David Harris',
    owner: 'pid8',

    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    recordId: 'randomId9',
    recordType: 'urgent',
    smokingStatus: 'non-smoker',
    pregnancyStatus: 'not pregnant',
    chronicCondition: 'none',
    currentMedications: 'None',
    allergies: 'None',
    chiefComplaint: 'chest pain',

    vitals: {
      temperature: 98.5,
      systolicBloodPressure: 130,
      diastolicBloodPressure: 85,
      pulse: 80,
      oxygen: 96,
      glucose: 92,
    },

    soap: {
      subjective: 'Patient reports intermittent chest pain, especially after exertion.',
      objective: 'Normal heart sounds, no murmurs, EKG ordered.',
      assessment: 'Possible angina, further testing needed to rule out cardiac issues.',
    },

    providerName: 'Dr. George Thompson',
    scribeName: 'Sarah White',
    owner: 'pid9',

    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    recordId: 'randomId10',
    recordType: 'standard',
    smokingStatus: 'non-smoker',
    pregnancyStatus: 'not pregnant',
    chronicCondition: 'vertigo',
    currentMedications: 'Meclizine',
    allergies: 'None',
    chiefComplaint: 'dizziness',

    vitals: {
      temperature: 98.0,
      systolicBloodPressure: 115,
      diastolicBloodPressure: 74,
      pulse: 70,
      oxygen: 97,
      glucose: 90,
    },

    soap: {
      subjective: 'Patient reports dizziness, especially when changing positions.',
      objective: 'Romberg test positive, mild nystagmus observed.',
      assessment: 'Vertigo, likely benign paroxysmal positional vertigo (BPPV).',
    },

    providerName: 'Dr. Victoria Martinez',
    scribeName: 'Chris Evans',
    owner: 'pid10',

    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    recordId: 'randomId11',
    recordType: 'standard',
    smokingStatus: 'non-smoker',
    pregnancyStatus: 'not pregnant',
    chronicCondition: 'none',
    currentMedications: 'None',
    allergies: 'None',
    chiefComplaint: 'fatigue and weakness',

    vitals: {
      temperature: 98.4,
      systolicBloodPressure: 118,
      diastolicBloodPressure: 77,
      pulse: 72,
      oxygen: 97,
      glucose: 86,
    },

    soap: {
      subjective: 'Patient reports feeling fatigued and weak for the past two weeks.',
      objective: 'No acute distress, slight pallor noted.',
      assessment: 'Fatigue, possible anemia, recommend CBC and further evaluation.',
    },

    providerName: 'Dr. Olivia Clark',
    scribeName: 'Tom Black',
    owner: 'pid11',

    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    recordId: 'randomId12',
    recordType: 'standard',
    smokingStatus: 'non-smoker',
    pregnancyStatus: 'not pregnant',
    chronicCondition: 'none',
    currentMedications: 'Antihistamines',
    allergies: 'Peanuts',
    chiefComplaint: 'allergic reaction',

    vitals: {
      temperature: 98.6,
      systolicBloodPressure: 122,
      diastolicBloodPressure: 80,
      pulse: 76,
      oxygen: 97,
      glucose: 88,
    },

    soap: {
      subjective: 'Patient reports hives and swelling after eating peanuts.',
      objective: 'Urticaria observed on skin, no respiratory distress.',
      assessment: 'Allergic reaction, administer antihistamine, monitor closely.',
    },

    providerName: 'Dr. Michael Davis',
    scribeName: 'Emily Thompson',
    owner: 'pid12',

    createdAt: new Date(),
    updatedAt: new Date(),
  },
];
