name: CI
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  style-check:
    name: Style Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          npm ci

      - name: Run Style Check
        run: |
          npm run format:check
